dataset: ICAfBIRN
model: CFDSVAE

local_size: 2
context_size: 2
contrastive_dim: 2

num_layers: 3
spatial_hidden_size: 128
temporal_hidden_size: 256

lr: 0.001
beta: 0.0001
gamma: 0.0
theta: 0.0
batch_size: 64
seed: 101010

data_size: 53
window_size: 20
window_step: 5
